# Generated by Django 5.0.4 on 2024-04-10 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuItem',
            new_name='MenuElement',
        ),
    ]
