# Generated by Django 5.0.4 on 2024-04-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0002_rename_menuitem_menuelement'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuelement',
            name='name_menu',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
