# Generated by Django 5.0.4 on 2024-04-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0003_menuelement_name_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuelement',
            name='name_menu',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
